const animate = require("tailwindcss-animate")

const calc = (num) => `calc(${num} * var(--webpage-summary-panel-srem))`;
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  safelist: ["dark"],
  prefix: "",

  content: [
    './src/**/*.{ts,tsx,vue}',
    './entrypoints/**/*.{ts,tsx,vue}',
  ],

  theme: {
    container: {
      center: true,
      padding: "2em",
      screens: {
        "2xl": "1400px",
      },
    },
    //https://github.com/tailwindlabs/tailwindcss/discussions/3768#discussioncomment-11339252
    borderRadius: {
      none: '0px',
      sm: calc(0.125),
      DEFAULT: calc(0.25),
      md: calc(0.375),
      lg: calc(0.5),
      xl: calc(0.75),
      '2xl': calc(1),
      '3xl': calc(1.5),
      full: '9999px',
    },

    columns: {
      auto: 'auto',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12',
      '3xs': calc(16),
      '2xs': calc(18),
      xs: calc(20),
      sm: calc(24),
      md: calc(28),
      lg: calc(32),
      xl: calc(36),
      '2xl': calc(42),
      '3xl': calc(48),
      '4xl': calc(56),
      '5xl': calc(64),
      '6xl': calc(72),
      '7xl': calc(80),
    },

    fontSize: {
      xs: [calc(0.75), { lineHeight: calc(1) }],
      sm: [calc(0.875), { lineHeight: calc(1.25) }],
      base: [calc(1), { lineHeight: calc(1.5) }],
      lg: [calc(1.125), { lineHeight: calc(1.75) }],
      xl: [calc(1.25), { lineHeight: calc(1.75) }],
      '2xl': [calc(1.5), { lineHeight: calc(2) }],
      '3xl': [calc(1.875), { lineHeight: calc(2.25) }],
      '4xl': [calc(2.25), { lineHeight: calc(2.5) }],
      '5xl': [calc(3), { lineHeight: '1' }],
      '6xl': [calc(3.75), { lineHeight: '1' }],
      '7xl': [calc(4.5), { lineHeight: '1' }],
      '8xl': [calc(6), { lineHeight: '1' }],
      '9xl': [calc(8), { lineHeight: '1' }],
    },

    lineHeight: {
      none: '1',
      tight: '1.25',
      snug: '1.375',
      normal: '1.5',
      relaxed: '1.625',
      loose: '2',
      3: calc(.75),
      4: calc(1),
      5: calc(1.25),
      6: calc(1.5),
      7: calc(1.75),
      8: calc(2),
      9: calc(2.25),
      10: calc(2.5),
    },

    maxWidth: ({ theme, breakpoints }) => ({
      ...theme('spacing'),
      none: 'none',
      xs: calc(20),
      sm: calc(24),
      md: calc(28),
      lg: calc(32),
      xl: calc(36),
      '2xl': calc(42),
      '3xl': calc(48),
      '4xl': calc(56),
      '5xl': calc(64),
      '6xl': calc(72),
      '7xl': calc(80),
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      prose: '65ch',
      ...breakpoints(theme('screens')),
    }),
    spacing: {
      px: '1px',
      0: '0px',
      0.5: calc(0.125),
      1: calc(0.25),
      1.5: calc(0.375),
      2: calc(0.5),
      2.5: calc(0.625),
      3: calc(0.75),
      3.5: calc(0.875),
      4: calc(1),
      5: calc(1.25),
      6: calc(1.5),
      7: calc(1.75),
      8: calc(2),
      9: calc(2.25),
      10: calc(2.5),
      11: calc(2.75),
      12: calc(3),
      14: calc(3.5),
      16: calc(4),
      20: calc(5),
      24: calc(6),
      28: calc(7),
      32: calc(8),
      36: calc(9),
      40: calc(10),
      44: calc(11),
      48: calc(12),
      52: calc(13),
      56: calc(14),
      60: calc(15),
      64: calc(16),
      72: calc(18),
      80: calc(20),
      96: calc(24),
    },


    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        hover: "hsl(var(--hover))",
        active: "hsl(var(--active))",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "collapsible-down": {
          from: { height: 0 },
          to: { height: 'var(--radix-collapsible-content-height)' },
        },
        "collapsible-up": {
          from: { height: 'var(--radix-collapsible-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "collapsible-down": "collapsible-down 0.2s ease-in-out",
        "collapsible-up": "collapsible-up 0.2s ease-in-out",
      },
    },
  },
  plugins: [animate],
}