name: Release

on:
    
  push:
    tags:
      - "*"
    # branches:
    #   - deploy-test
permissions: 
  contents: write
jobs:
  submit:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: packages/ext

      - name: Zip extensions
        run: |
          pnpm zip
          pnpm zip:edge
          pnpm zip:firefox
        working-directory: packages/ext
  
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            packages/ext/.output/*-chrome.zip
            packages/ext/.output/*-edge.zip
            packages/ext/.output/*-firefox.zip


      - name: Submit to stores
        run: |
          pnpm wxt submit \
            --chrome-zip .output/*-chrome.zip \
            --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip \
            --edge-zip   .output/*-edge.zip
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          EDGE_PRODUCT_ID:  ${{secrets.EDGE_PRODUCT_ID}}
          EDGE_CLIENT_ID: ${{secrets.EDGE_CLIENT_ID}}
          EDGE_API_KEY: ${{secrets.EDGE_API_KEY }}
          EDGE_API_VERSION: 1.1
      
        working-directory: packages/ext
